server:
  port: 7001

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true  #显示访问路径的 ip 地址
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #服务注册中心
